name: Send email on push

on: [push]   # срабатывает при каждом push

jobs:
  send-mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Новый push в репозитории ${{ github.repository }}"
          to: "example@mail.com"
          from: "GitHub Actions <${{ secrets.MAIL_USERNAME }}>"
          body: |
            ✅ Репозиторий: ${{ github.repository }}
            👤 Автор: ${{ github.event.pusher.name }}
            📝 Сообщение коммита: ${{ github.event.head_commit.message }}
